#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Formula)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(gam)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(gamlss)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(gamlss.data)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(gamlss.dist)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(gcrma)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(gdata)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(gee)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(geepack)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(GenABEL)"
