#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(GenABEL.data)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(genefilter)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(geneLenDataBase)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(geneplotter)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(GeneR)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(genetics)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(GenomicFeatures)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(GenomicRanges)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(GEOquery)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(ggplot2)"
