#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(hmutil)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(htmltools)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(httpuv)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(IRanges)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(IST)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(ISTcore)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(ISTplots)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(jsonlite)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(labeling)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(lazyeval)"
