#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(sp)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(spam)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(SparseM)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(spatial)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(splines)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(stabledist)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(statmod)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(statnet.common)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(stats)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(stats4)"
