#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(magrittr)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(MASS)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(mime)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(munsell)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Nozzle.R1)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(plotrix)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(plyr)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(proto)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(R6)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(raster)"
