#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(annotate)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(AnnotationDbi)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(anutil)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(ape)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(aplpack)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(arm)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(aroma.affymetrix)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(aroma.apd)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(aroma.core)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(aroma.light)"
