#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(svMisc)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(svSocket)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(svSweave)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(svTools)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(svUnit)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(svWidgets)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(synapseClient)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(tcltk2.bak)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(tensorA)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(TH.data)"
