#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(quantsmooth)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(R2HTML)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(R2WinBUGS)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(randomForest)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(randomSurvivalForest)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RankProd)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(raster)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RBGL)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(R.cache)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(rcdk)"
