#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(CircStats)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(class)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(ClassDiscovery)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(cluster)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(clusterGeneration)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(coda)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(codetools)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(colorspace)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(combinat)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(compiler)"
