#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(MEDME)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(memoise)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(MetABEL)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(methods)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(mgcv)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(mi)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(micma)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(miller)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(minpack.lm)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(minqa)"
