#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(convert)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(corpcor)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(corrplot)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(cubature)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(DatABEL)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(datasets)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(DBI)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(deal)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(dichromat)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(digest)"
