#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(annotate)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(AnnotationDbi)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(anutil)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(assertthat)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(beeswarm)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(BH)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Biobase)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(biomaRt)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(dichromat)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(digest)"
