#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(ellipse)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(epiR)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(evaluate)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(fastcluster)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(fBasics)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(fields)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(fingerprint)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(foreach)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(foreign)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(formatR)"
