#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(miscTools)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(mlbench)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(modeltools)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(moments)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(muhaz)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(multcomp)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(multtest)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(munsell)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(mvtnorm)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(NCBI2R)"
