#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RPMG)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(rPython)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(rrcov)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(R.rsp)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Rsamtools)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RSEIS)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Rserve)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RSQLite)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(rtracklayer)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RUnit)"
