#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(directlabels)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(DNAcopy)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(doBy)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(doSNOW)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(drc)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(DynDoc)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(e1071)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Ecdat)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(edgeR)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(effects)"
