#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(rgl)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Rgraphviz)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(R.huge)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RISmed)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(rJava)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RJDBC)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(rjson)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(RJSONIO)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Rlab)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(rlecuyer)"
