#!/bin/bash
R -q -e "source('/res/dyn_lib_load.R'); load_lib(car)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(caret)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(Category)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(caTools)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(CGHbase)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(CGHcall)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(CGHregions)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(ChemmineOB)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(ChemmineR)"
R -q -e "source('/res/dyn_lib_load.R'); load_lib(chron)"
