#!/bin/bash
sudo apt-cache search r-cran-annotate
sudo apt-cache search r-cran-AnnotationDbi
sudo apt-cache search r-cran-anutil
sudo apt-cache search r-cran-assertthat
sudo apt-cache search r-cran-beeswarm
sudo apt-cache search r-cran-BH
sudo apt-cache search r-cran-Biobase
sudo apt-cache search r-cran-biomaRt
sudo apt-cache search r-cran-dichromat
sudo apt-cache search r-cran-digest
sudo apt-cache search r-cran-dplyr
sudo apt-cache search r-cran-gdata
sudo apt-cache search r-cran-ggplot2
sudo apt-cache search r-cran-ggvis
sudo apt-cache search r-cran-GO.db
sudo apt-cache search r-cran-gplots
sudo apt-cache search r-cran-gtable
sudo apt-cache search r-cran-GTI
sudo apt-cache search r-cran-gtools
sudo apt-cache search r-cran-Heatplus
sudo apt-cache search r-cran-hmutil
sudo apt-cache search r-cran-htmltools
sudo apt-cache search r-cran-httpuv
sudo apt-cache search r-cran-IRanges
sudo apt-cache search r-cran-IST
sudo apt-cache search r-cran-ISTcore
sudo apt-cache search r-cran-ISTplots
sudo apt-cache search r-cran-jsonlite
sudo apt-cache search r-cran-labeling
sudo apt-cache search r-cran-lazyeval
sudo apt-cache search r-cran-magrittr
sudo apt-cache search r-cran-MASS
sudo apt-cache search r-cran-mime
sudo apt-cache search r-cran-munsell
sudo apt-cache search r-cran-Nozzle.R1
sudo apt-cache search r-cran-plotrix
sudo apt-cache search r-cran-plyr
sudo apt-cache search r-cran-proto
sudo apt-cache search r-cran-R6
sudo apt-cache search r-cran-raster
sudo apt-cache search r-cran-RColorBrewer
sudo apt-cache search r-cran-Rcpp
sudo apt-cache search r-cran-RCurl
sudo apt-cache search r-cran-reshape
sudo apt-cache search r-cran-reshape2
sudo apt-cache search r-cran-RJSONIO
sudo apt-cache search r-cran-rPython
sudo apt-cache search r-cran-RSQLite
sudo apt-cache search r-cran-scales
sudo apt-cache search r-cran-scatterplot3d
sudo apt-cache search r-cran-shiny
sudo apt-cache search r-cran-shinydashboard
sudo apt-cache search r-cran-sp
sudo apt-cache search r-cran-statutils
sudo apt-cache search r-cran-stringi
sudo apt-cache search r-cran-stringr
sudo apt-cache search r-cran-vcd
sudo apt-cache search r-cran-venn
sudo apt-cache search r-cran-vttutil
sudo apt-cache search r-cran-XLConnect
sudo apt-cache search r-cran-XLConnectJars
sudo apt-cache search r-cran-xlsx
sudo apt-cache search r-cran-xlsxjars
sudo apt-cache search r-cran-XML
sudo apt-cache search r-cran-xtable
sudo apt-cache search r-cran-ABarray
sudo apt-cache search r-cran-abind
sudo apt-cache search r-cran-affxparser
sudo apt-cache search r-cran-affy
sudo apt-cache search r-cran-affydata
sudo apt-cache search r-cran-affyio
sudo apt-cache search r-cran-affyPara
sudo apt-cache search r-cran-affyPLM
sudo apt-cache search r-cran-affyQCReport
sudo apt-cache search r-cran-akima
sudo apt-cache search r-cran-AlgDesign
sudo apt-cache search r-cran-alr3
sudo apt-cache search r-cran-amap
sudo apt-cache search r-cran-analogue
sudo apt-cache search r-cran-annaffy
sudo apt-cache search r-cran-annotate
sudo apt-cache search r-cran-AnnotationDbi
sudo apt-cache search r-cran-anutil
sudo apt-cache search r-cran-ape
sudo apt-cache search r-cran-aplpack
sudo apt-cache search r-cran-arm
sudo apt-cache search r-cran-aroma.affymetrix
sudo apt-cache search r-cran-aroma.apd
sudo apt-cache search r-cran-aroma.core
sudo apt-cache search r-cran-aroma.light
sudo apt-cache search r-cran-ArrayTools
sudo apt-cache search r-cran-aws
sudo apt-cache search r-cran-awsMethods
sudo apt-cache search r-cran-base
sudo apt-cache search r-cran-base64enc
sudo apt-cache search r-cran-beadarray
sudo apt-cache search r-cran-BeadDataPackR
sudo apt-cache search r-cran-beeswarm
sudo apt-cache search r-cran-BiasedUrn
sudo apt-cache search r-cran-Biobase
sudo apt-cache search r-cran-BiocGenerics
sudo apt-cache search r-cran-BiocInstaller
sudo apt-cache search r-cran-biomaRt
sudo apt-cache search r-cran-Biostrings
sudo apt-cache search r-cran-bitops
sudo apt-cache search r-cran-biwt
sudo apt-cache search r-cran-boot
sudo apt-cache search r-cran-bootstrap
sudo apt-cache search r-cran-BSgenome
sudo apt-cache search r-cran-Cairo
sudo apt-cache search r-cran-car
sudo apt-cache search r-cran-caret
sudo apt-cache search r-cran-Category
sudo apt-cache search r-cran-caTools
sudo apt-cache search r-cran-CGHbase
sudo apt-cache search r-cran-CGHcall
sudo apt-cache search r-cran-CGHregions
sudo apt-cache search r-cran-ChemmineOB
sudo apt-cache search r-cran-ChemmineR
sudo apt-cache search r-cran-chron
sudo apt-cache search r-cran-CircStats
sudo apt-cache search r-cran-class
sudo apt-cache search r-cran-ClassDiscovery
sudo apt-cache search r-cran-cluster
sudo apt-cache search r-cran-clusterGeneration
sudo apt-cache search r-cran-coda
sudo apt-cache search r-cran-codetools
sudo apt-cache search r-cran-colorspace
sudo apt-cache search r-cran-combinat
sudo apt-cache search r-cran-compiler
sudo apt-cache search r-cran-convert
sudo apt-cache search r-cran-corpcor
sudo apt-cache search r-cran-corrplot
sudo apt-cache search r-cran-cubature
sudo apt-cache search r-cran-DatABEL
sudo apt-cache search r-cran-datasets
sudo apt-cache search r-cran-DBI
sudo apt-cache search r-cran-deal
sudo apt-cache search r-cran-dichromat
sudo apt-cache search r-cran-digest
sudo apt-cache search r-cran-directlabels
sudo apt-cache search r-cran-DNAcopy
sudo apt-cache search r-cran-doBy
sudo apt-cache search r-cran-doSNOW
sudo apt-cache search r-cran-drc
sudo apt-cache search r-cran-DynDoc
sudo apt-cache search r-cran-e1071
sudo apt-cache search r-cran-Ecdat
sudo apt-cache search r-cran-edgeR
sudo apt-cache search r-cran-effects
sudo apt-cache search r-cran-ellipse
sudo apt-cache search r-cran-epiR
sudo apt-cache search r-cran-evaluate
sudo apt-cache search r-cran-fastcluster
sudo apt-cache search r-cran-fBasics
sudo apt-cache search r-cran-fields
sudo apt-cache search r-cran-fingerprint
sudo apt-cache search r-cran-foreach
sudo apt-cache search r-cran-foreign
sudo apt-cache search r-cran-formatR
sudo apt-cache search r-cran-Formula
sudo apt-cache search r-cran-gam
sudo apt-cache search r-cran-gamlss
sudo apt-cache search r-cran-gamlss.data
sudo apt-cache search r-cran-gamlss.dist
sudo apt-cache search r-cran-gcrma
sudo apt-cache search r-cran-gdata
sudo apt-cache search r-cran-gee
sudo apt-cache search r-cran-geepack
sudo apt-cache search r-cran-GenABEL
sudo apt-cache search r-cran-GenABEL.data
sudo apt-cache search r-cran-genefilter
sudo apt-cache search r-cran-geneLenDataBase
sudo apt-cache search r-cran-geneplotter
sudo apt-cache search r-cran-GeneR
sudo apt-cache search r-cran-genetics
sudo apt-cache search r-cran-GenomicFeatures
sudo apt-cache search r-cran-GenomicRanges
sudo apt-cache search r-cran-GEOquery
sudo apt-cache search r-cran-ggplot2
sudo apt-cache search r-cran-GlobalDeviance
sudo apt-cache search r-cran-gmodels
sudo apt-cache search r-cran-GO.db
sudo apt-cache search r-cran-golubEsets
sudo apt-cache search r-cran-googleVis
sudo apt-cache search r-cran-goseq
sudo apt-cache search r-cran-gplots
sudo apt-cache search r-cran-graph
sudo apt-cache search r-cran-graphics
sudo apt-cache search r-cran-grDevices
sudo apt-cache search r-cran-grid
sudo apt-cache search r-cran-gridExtra
sudo apt-cache search r-cran-GSEABase
sudo apt-cache search r-cran-gsl
sudo apt-cache search r-cran-gsmoothr
sudo apt-cache search r-cran-gss
sudo apt-cache search r-cran-gtable
sudo apt-cache search r-cran-GTI
sudo apt-cache search r-cran-gtools
sudo apt-cache search r-cran-Heatplus
sudo apt-cache search r-cran-hgu133acdf
sudo apt-cache search r-cran-hgu133ahsensgcdf
sudo apt-cache search r-cran-hgu133aprobe
sudo apt-cache search r-cran-hgu133plus2cdf
sudo apt-cache search r-cran-hgu133plus2hsentrezgcdf
sudo apt-cache search r-cran-hgu133plus2probe
sudo apt-cache search r-cran-hgu95av2.db
sudo apt-cache search r-cran-highr
sudo apt-cache search r-cran-Hmisc
sudo apt-cache search r-cran-hmutil
sudo apt-cache search r-cran-hopach
sudo apt-cache search r-cran-hwriter
sudo apt-cache search r-cran-igraph
sudo apt-cache search r-cran-igraph0
sudo apt-cache search r-cran-illuminaHumanv3BeadID.db
sudo apt-cache search r-cran-illuminaHumanv3.db
sudo apt-cache search r-cran-impute
sudo apt-cache search r-cran-ineq
sudo apt-cache search r-cran-ipred
sudo apt-cache search r-cran-IRanges
sudo apt-cache search r-cran-IST
sudo apt-cache search r-cran-ISTcore
sudo apt-cache search r-cran-ISTplots
sudo apt-cache search r-cran-iterators
sudo apt-cache search r-cran-itertools
sudo apt-cache search r-cran-its
sudo apt-cache search r-cran-KEGG.db
sudo apt-cache search r-cran-KernSmooth
sudo apt-cache search r-cran-knitr
sudo apt-cache search r-cran-labdsv
sudo apt-cache search r-cran-labeling
sudo apt-cache search r-cran-lasso2
sudo apt-cache search r-cran-latentnet
sudo apt-cache search r-cran-lattice
sudo apt-cache search r-cran-latticeExtra
sudo apt-cache search r-cran-leaps
sudo apt-cache search r-cran-limma
sudo apt-cache search r-cran-lme4
sudo apt-cache search r-cran-lmtest
sudo apt-cache search r-cran-locfit
sudo apt-cache search r-cran-magic
sudo apt-cache search r-cran-maps
sudo apt-cache search r-cran-markdown
sudo apt-cache search r-cran-marray
sudo apt-cache search r-cran-MASS
sudo apt-cache search r-cran-Matrix
sudo apt-cache search r-cran-matrixcalc
sudo apt-cache search r-cran-matrixStats
sudo apt-cache search r-cran-MCMCglmm
sudo apt-cache search r-cran-MCRestimate
sudo apt-cache search r-cran-MEDME
sudo apt-cache search r-cran-memoise
sudo apt-cache search r-cran-MetABEL
sudo apt-cache search r-cran-methods
sudo apt-cache search r-cran-mgcv
sudo apt-cache search r-cran-mi
sudo apt-cache search r-cran-micma
sudo apt-cache search r-cran-miller
sudo apt-cache search r-cran-minpack.lm
sudo apt-cache search r-cran-minqa
sudo apt-cache search r-cran-miscTools
sudo apt-cache search r-cran-mlbench
sudo apt-cache search r-cran-modeltools
sudo apt-cache search r-cran-moments
sudo apt-cache search r-cran-muhaz
sudo apt-cache search r-cran-multcomp
sudo apt-cache search r-cran-multtest
sudo apt-cache search r-cran-munsell
sudo apt-cache search r-cran-mvtnorm
sudo apt-cache search r-cran-NCBI2R
sudo apt-cache search r-cran-NeatMap
sudo apt-cache search r-cran-network
sudo apt-cache search r-cran-nlme
sudo apt-cache search r-cran-nnet
sudo apt-cache search r-cran-Nozzle.R1
sudo apt-cache search r-cran-np
sudo apt-cache search r-cran-nplplot
sudo apt-cache search r-cran-oompaBase
sudo apt-cache search r-cran-org.Hs.eg.db
sudo apt-cache search r-cran-orthopolynom
sudo apt-cache search r-cran-pamr
sudo apt-cache search r-cran-parallel
sudo apt-cache search r-cran-pastecs
sudo apt-cache search r-cran-pcaPP
sudo apt-cache search r-cran-permute
sudo apt-cache search r-cran-pixmap
sudo apt-cache search r-cran-plotrix
sudo apt-cache search r-cran-plyr
sudo apt-cache search r-cran-png
sudo apt-cache search r-cran-polynom
sudo apt-cache search r-cran-PreProcess
sudo apt-cache search r-cran-preprocessCore
sudo apt-cache search r-cran-princurve
sudo apt-cache search r-cran-prodlim
sudo apt-cache search r-cran-proto
sudo apt-cache search r-cran-proxy
sudo apt-cache search r-cran-PSCBS
sudo apt-cache search r-cran-pscl
sudo apt-cache search r-cran-quadprog
sudo apt-cache search r-cran-quantreg
sudo apt-cache search r-cran-quantsmooth
sudo apt-cache search r-cran-R2HTML
sudo apt-cache search r-cran-R2WinBUGS
sudo apt-cache search r-cran-randomForest
sudo apt-cache search r-cran-randomSurvivalForest
sudo apt-cache search r-cran-RankProd
sudo apt-cache search r-cran-raster
sudo apt-cache search r-cran-RBGL
sudo apt-cache search r-cran-R.cache
sudo apt-cache search r-cran-rcdk
sudo apt-cache search r-cran-rcdklibs
sudo apt-cache search r-cran-RColorBrewer
sudo apt-cache search r-cran-Rcpp
sudo apt-cache search r-cran-RcppArmadillo
sudo apt-cache search r-cran-RCurl
sudo apt-cache search r-cran-R.devices
sudo apt-cache search r-cran-rEMM
sudo apt-cache search r-cran-reshape
sudo apt-cache search r-cran-reshape2
sudo apt-cache search r-cran-R.filesets
sudo apt-cache search r-cran-rgl
sudo apt-cache search r-cran-Rgraphviz
sudo apt-cache search r-cran-R.huge
sudo apt-cache search r-cran-RISmed
sudo apt-cache search r-cran-rJava
sudo apt-cache search r-cran-RJDBC
sudo apt-cache search r-cran-rjson
sudo apt-cache search r-cran-RJSONIO
sudo apt-cache search r-cran-Rlab
sudo apt-cache search r-cran-rlecuyer
sudo apt-cache search r-cran-rmeta
sudo apt-cache search r-cran-R.methodsS3
sudo apt-cache search r-cran-rms
sudo apt-cache search r-cran-RMySQL
sudo apt-cache search r-cran-robustbase
sudo apt-cache search r-cran-ROC
sudo apt-cache search r-cran-ROCR
sudo apt-cache search r-cran-R.oo
sudo apt-cache search r-cran-ROracle
sudo apt-cache search r-cran-rpart
sudo apt-cache search r-cran-RPMG
sudo apt-cache search r-cran-rPython
sudo apt-cache search r-cran-rrcov
sudo apt-cache search r-cran-R.rsp
sudo apt-cache search r-cran-Rsamtools
sudo apt-cache search r-cran-RSEIS
sudo apt-cache search r-cran-Rserve
sudo apt-cache search r-cran-RSQLite
sudo apt-cache search r-cran-rtracklayer
sudo apt-cache search r-cran-RUnit
sudo apt-cache search r-cran-R.utils
sudo apt-cache search r-cran-Rwave
sudo apt-cache search r-cran-sandwich
sudo apt-cache search r-cran-scales
sudo apt-cache search r-cran-scatterplot3d
sudo apt-cache search r-cran-SciViews
sudo apt-cache search r-cran-sem
sudo apt-cache search r-cran-sendmailR
sudo apt-cache search r-cran-seqinr
sudo apt-cache search r-cran-sessionTools
sudo apt-cache search r-cran-sfit
sudo apt-cache search r-cran-shapes
sudo apt-cache search r-cran-ShortRead
sudo apt-cache search r-cran-simpleaffy
sudo apt-cache search r-cran-slam
sudo apt-cache search r-cran-sm
sudo apt-cache search r-cran-sna
sudo apt-cache search r-cran-snow
sudo apt-cache search r-cran-snowfall
sudo apt-cache search r-cran-som
sudo apt-cache search r-cran-sp
sudo apt-cache search r-cran-spam
sudo apt-cache search r-cran-SparseM
sudo apt-cache search r-cran-spatial
sudo apt-cache search r-cran-splines
sudo apt-cache search r-cran-stabledist
sudo apt-cache search r-cran-statmod
sudo apt-cache search r-cran-statnet.common
sudo apt-cache search r-cran-stats
sudo apt-cache search r-cran-stats4
sudo apt-cache search r-cran-statutils
sudo apt-cache search r-cran-stringr
sudo apt-cache search r-cran-SuppDists
sudo apt-cache search r-cran-survcomp
sudo apt-cache search r-cran-survival
sudo apt-cache search r-cran-survivalROC
sudo apt-cache search r-cran-svDialogs
sudo apt-cache search r-cran-svGUI
sudo apt-cache search r-cran-svIDE
sudo apt-cache search r-cran-svKomodo
sudo apt-cache search r-cran-svMisc
sudo apt-cache search r-cran-svSocket
sudo apt-cache search r-cran-svSweave
sudo apt-cache search r-cran-svTools
sudo apt-cache search r-cran-svUnit
sudo apt-cache search r-cran-svWidgets
sudo apt-cache search r-cran-synapseClient
sudo apt-cache search r-cran-tcltk2.bak
sudo apt-cache search r-cran-tensorA
sudo apt-cache search r-cran-TH.data
sudo apt-cache search r-cran-timeDate
sudo apt-cache search r-cran-timeSeries
sudo apt-cache search r-cran-tools
sudo apt-cache search r-cran-tweedie
sudo apt-cache search r-cran-u133aaofav2cdf
sudo apt-cache search r-cran-urca
sudo apt-cache search r-cran-utils
sudo apt-cache search r-cran-vcd
sudo apt-cache search r-cran-vegan
sudo apt-cache search r-cran-venn
sudo apt-cache search r-cran-VennDiagram
sudo apt-cache search r-cran-verification
sudo apt-cache search r-cran-vioplot
sudo apt-cache search r-cran-vsn
sudo apt-cache search r-cran-vttutil
sudo apt-cache search r-cran-waveslim
sudo apt-cache search r-cran-wordcloud
sudo apt-cache search r-cran-XLConnect
sudo apt-cache search r-cran-XLConnectJars
sudo apt-cache search r-cran-xlsx
sudo apt-cache search r-cran-xlsxjars
sudo apt-cache search r-cran-XML
sudo apt-cache search r-cran-xtable
sudo apt-cache search r-cran-zlibbioc
sudo apt-cache search r-cran-zoo
